### PR TITLE
Added some more calls

### PR DESCRIPTION
**Pull request by CurtTilmes**
Just fleshing out some more calls to libarchive.

### CODE REVIEW

**Review by frithnanth — COMMENTED** [review]
I appreciate very much your taking the time to review this module and add some code!
Do you have any test case for the new subs that I can add while merging?

**Comment by CurtTilmes** [comment]
Added tests for almost all new calls.

**Comment by frithnanth** [comment]
Excellent, thank you!

**Comment by frithnanth** [comment]
archive_entry_size() works fine on my computer (Debian sid), but fails on TravisCI (Ubuntu xenial).
Probably it depends on the version of the underlying library. I will look into it as soon as I can; if you have any idea, let me know.

**Comment by CurtTilmes** [comment]
weird -- I'm running Ubuntu xenial...

**Pull request merged**
